const services = [
    { value: "all4", label: "All4", color: "#ED1B2D" },
    { value: "apple", label: "Apple", color: "#A6B1B7" },
    { value: "britbox", label: "Britbox", color: "#1F2D3D" },
    { value: "crave", label: "Crave", color: "#DF0031" },
    { value: "curiosity", label: "Curiosity", color: "#FF5800" },
    { value: "disney", label: "Disney", color: "#003DA5" },
    { value: "hbo", label: "HBO", color: "#3820FF" },
    { value: "hotstar", label: "Hotstar", color: "#FFA800" },
    { value: "hulu", label: "Hulu", color: "#1CE783" },
    { value: "iplayer", label: "Iplayer", color: "#F54997" },
    { value: "mubi", label: "Mubi", color: "#18453B" },
    { value: "netflix", label: "Netflix", color: "#E50914" },
    { value: "now", label: "Now", color: "#FF8200" },
    { value: "paramount", label: "Paramount+", color: "#0039C6" },
    { value: "peacock", label: "Peacock", color: "#00A4E4" },
    { value: "prime", label: "Prime", color: "#00A8E1" },
    { value: "showtime", label: "Showtime", color: "#C40000" },
    { value: "stan", label: "Stan", color: " #E60032" },
    { value: "starz", label: "Starz", color: "#FFC800" },
    { value: "wow", label: "Wow", color: "#5E268D" },
    { value: "zee5", label: "Zee5", color: "#FF0000" },
];

const countries = [
    { value: "ae", label: "United Emirates" },
    { value: "ar", label: "Argentina" },
    { value: "at", label: "Austria" },
    { value: "au", label: "Australia" },
    { value: "az", label: "Azerbaijan" },
    { value: "be", label: "Belgium" },
    { value: "bg", label: "Bulgaria" },
    { value: "br", label: "Brazil" },
    { value: "ca", label: "Canada" },
    { value: "ch", label: "Switzerland" },
    { value: "cl", label: "Chile" },
    { value: "co", label: "Colombia" },
    { value: "cy", label: "Cyprus" },
    { value: "cz", label: "Czech Republic" },
    { value: "de", label: "Germany" },
    { value: "dk", label: "Denmark" },
    { value: "ec", label: "Ecuador" },
    { value: "ee", label: "Estonia" },
    { value: "es", label: "Spain" },
    { value: "fi", label: "Finland" },
    { value: "fr", label: "France" },
    { value: "gb", label: "United Kingdom" },
    { value: "gr", label: "Greece" },
    { value: "hk", label: "Hong Kong" },
    { value: "hr", label: "Croatia" },
    { value: "hu", label: "Hungary" },
    { value: "id", label: "Indonesia" },
    { value: "ie", label: "Ireland" },
    { value: "il", label: "Israel" },
    { value: "in", label: "India" },
    { value: "is", label: "Iceland" },
    { value: "it", label: "Italy" },
    { value: "jp", label: "Japan" },
    { value: "kr", label: "South Korea" },
    { value: "lt", label: "Lithuania" },
    { value: "md", label: "Moldova" },
    { value: "mk", label: "North Macedonia" },
    { value: "mx", label: "Mexico" },
    { value: "my", label: "Malaysia" },
    { value: "nl", label: "Netherlands" },
    { value: "no", label: "Norway" },
    { value: "nz", label: "New Zealand" },
    { value: "pa", label: "Panama" },
    { value: "pe", label: "Peru" },
    { value: "ph", label: "Philippines" },
    { value: "pl", label: "Poland" },
    { value: "pt", label: "Portugal" },
    { value: "ro", label: "Romania" },
    { value: "rs", label: "Serbia" },
    { value: "ru", label: "Russia" },
    { value: "se", label: "Sweden" },
    { value: "sg", label: "Singapore" },
    { value: "th", label: "Thailand" },
    { value: "tr", label: "Turkey" },
    { value: "ua", label: "Ukraine" },
    { value: "us", label: "United States" },
    { value: "vn", label: "Vietnam" },
    { value: "za", label: "South Africa" },
];

export {services, countries}